### ISSUE TITLE
Missing support for Icomoon's feature for multiple class names

### ISSUE THREAD

**Issue by Shoplifter** [SAPikachu/icomoon-build#11]
When I use multiple class names in icomoon
e.g. "image-left-aligned, image-big" for the same icon:

I get this in icon-classes.scss:

`.icon-image-left-aligned, image-big:before { content: $icon-image-left-aligned, image-big-content; }`

where it should be:
```
.icon-image-left-aligned:before { content: $icon-image-left-aligned-content; }
.icon-image-big:before { content: $icon-image-big-content; }
```
or shorter:
`.icon-image-left-aligned:before, .icon-image-big:before { content: $icon-image-left-aligned-content; }`

There is also an error in the declaration of the content variables:
`$icon-image-left-aligned, image-big-variant-content: "\e800";`
instead of:
```
$icon-image-left-aligned-content: "\e800";
$icon-image-big-content: "\e800";
```

But that issue is of course easy to work around.

**Comment by SAPikachu** [comment]
Looks like this is a new feature of IcoMoon, can you post your project file here (or send to i@sapika.ch) so that I can be sure my fix is correct? Thanks. :)

**Comment by Shoplifter** [comment]
[test.zip](https://github.com/SAPikachu/icomoon-build/files/442605/test.zip)

you're welcome. Attached archive conzains *.json project file from icomoon and _icon-classes.scss generated by icomoon-build

**Comment by SAPikachu** [comment]
Thanks! I will look into it later this week.

**Comment by SAPikachu** [comment]
Just fixed in latest version, can you have a try?

**Comment by Shoplifter** [comment]
@SAPikachu 
Hi, sorry for the delyay, i have been on vacation last week. 
Declaration of SASS variables is fine now, but there's still a bug in the icon_classes mixin:
Instead of 

```
@mixin icon-classes {
    .icon-search:before { content: $icon-search, magnifier-content; }
    .icon-magnifier:before { content: $icon-search, magnifier-content; }
}
```
it should look like 
```
@mixin icon-classes {
    .icon-search:before { content: $icon-search-content; }
    .icon-magnifier:before { content: $icon-magnifier-content; }
}
```
[icomoon-test.zip](https://github.com/SAPikachu/icomoon-build/files/467484/icomoon-test.zip)

The archive attached contains the json file (test.json) and the archive downloaded from icomoon (incl. fonts, css, demo files etc. - test.zip

**Comment by SAPikachu** [comment]
Oops, sorry that I missed one change in the code. Should be fixed in the latest version, can you have a try?

**Comment by Shoplifter** [comment]
works great now. Thank you for fixing this!
